# information about data sets
# Path to the data
data_folder: "/Users/colmconnaughton/LML/Local/data/wind power/"
output_folder: "/Users/colmconnaughton/LML/Local/data/wind power/analysis"

# Low frequency data
dataset1:
  subfolder: "ScoutEnergyData/"
  windfarms:
    BTRG: "Bitter Ridge"
    HTX: "Heart of Texas"
    PC1: "Persimmon Creek 1"
    RNCH: "Ranchero"
  wind:
    subfolder : "Wind Speed and Direction/"
    filenames:
      BTRG: "BTRG_WindSpeedAndDirection_10min.csv"
      HTX: "HTX_WindSpeedAndDirection_10min.csv"
      PC1: "PC1_WindSpeedAndDirection_10min.csv"
      RNCH: "RNCH_WindSpeedAndDirection_10min.csv"


# High frequency data
dataset2:
  subfolder: "HowardData/"
  windfarms:
    "HWRD" : "Howard"
  filenames:
    - "Howard_WTG_1_&_2_data_for_jay_part_1.xlsx"
    - "Howard_WTG_1_&_2_data_for_jay_part_2.xlsx"
    - "Howard_WTG_1_&_2_data_for_jay_part_3.xlsx"
  excel_sheet_names:
    "wind" : "WTG 1 and 2 data"
    "meteo" : "Met tower data"
