# information about data sets
# Path to the data
data_folder: "/Users/colmconnaughton/LML/Local/data/wind power/"
output_folder: "/Users/colmconnaughton/LML/Local/data/wind power/analysis"

# Low frequency data
dataset1:
  subfolder: "ScoutEnergyData/"
  windfarms:
    BTRG: "Bitter Ridge"
    HTX: "Heart of Texas"
    PC1: "Persimmon Creek 1"
    RNCH: "Ranchero"
  wind:
    subfolder : "Wind Speed and Direction/"
    filenames:
      BTRG: "btrg_windspeed_COD_to_20230601.csv"
      HTX: "htx_windspeed_COD_to_20230601.csv"
      PC1: "pc1_windspeed_COD_to_20230601.csv"
      RNCH: "rnch_windspeed_COD_to_20230601.csv"
  direction:
    subfolder : "Wind Speed and Direction/"
    filenames:
      BTRG: "btrg_winddir_COD_to_20230601.csv"
      HTX: "htx_winddir_COD_to_20230601.csv"
      PC1: "pc1_winddir_COD_to_20230601.csv"
      RNCH: "rnch_winddir_COD_to_20230601.csv"
  power:
    subfolder : "Generation Files/"
    filenames:
      BTRG: "btr_prod_COD_to_20230601.csv"
      HTX: "htx_prod_COD_to_20230601_Common wtg names.csv"
      PC1: "pcw1_prod_COD_to_20230601.csv"
      RNCH: "rnch_prod_COD_to_20230511.csv"
  layout:
    subfolder: "Final As Built Layouts/"
    filenames:
      BTRG: "Bitter Ridge As Built WGS84 Lat Lon.csv"
      HTX: "Heart of Texas As Built WGS84 Lat Lon.csv"
      PC1: "Persimmon Creek 1 As Built WGS84 Lat Lon.csv"
      RNCH: "Ranchero As Built WGS84 Lat Lon.csv"


# High frequency data
dataset2:
  subfolder: "HowardData/"
  windfarms:
    "HWRD" : "Howard"
  filenames:
    - "Howard_WTG_1_&_2_data_for_jay_part_1.xlsx"
    - "Howard_WTG_1_&_2_data_for_jay_part_2.xlsx"
    - "Howard_WTG_1_&_2_data_for_jay_part_3.xlsx"
  excel_sheet_names:
    "wind" : "WTG 1 and 2 data"
    "meteo" : "Met tower data"
